name: taxi-out-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn=0.23.2
  - pandas=1.1.5
  - numpy=1.19.1
  - cloudpickle=1.6.0
  - mlflow=1.19
  - xgboost=1.2.0
  - kedro=0.16.2
  - psycopg2=2.8.5
  - scp=0.13.2
  - matplotlib=3.3.2
  - pytest-cov=2.10.1
  - seaborn=0.11.1
  - hyperopt=0.2.5
  - tensorflow=2.0.0
  - tensorboard=2.0.0
  - tensorflow-estimator=2.0.0
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - ipython_genutils=0.2.0
  - pip
  - pip:
    - git+https://github.com/nasa/ML-airport-data-services.git
